name: app_produtividade
description: A new Flutter project para TDAH, estudantes, profissionais, marombeiros que buscam ter uma rotina produtiva no seu dia dia com mais foco e menos ansiedade.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.2
  provider: ^6.0.5
  get_storage: ^2.1.1
  http: ^0.13.5
  archive: ^3.5.0
  youtube_player_flutter: ^8.1.2
  url_launcher: ^6.1.10
  percent_indicator: ^4.2.3
  dio: ^5.3.2
  flutter_markdown: ^0.7.1
  shared_preferences: ^2.2.1
  localstorage: ^4.0.1+4
  hive: ^2.2.3
  path_provider: ^2.1.1
  hive_flutter: ^1.1.0
  build_runner: ^2.4.6
  flutter_slidable: ^3.0.0
  table_calendar: ^3.0.9
  modal_bottom_sheet: ^2.1.2
  syncfusion_flutter_calendar: ^23.1.40
  glass_kit: ^3.0.0
  boardview: ^0.2.2
  file_picker: ^5.5.0
  open_file: ^3.3.2
  kanban_board: ^0.1.0
  universal_html: ^2.2.4
  asp: ^1.3.0
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.1
  google_generative_ai: ^0.0.1-dev
  flutter_gemini: ^2.0.3
  fluent_ui: ^1.2.3
  animated_text_kit: ^4.2.2
  flutter_drawing_board: ^0.7.0+2
  flutter_hooks: ^0.20.5
  image_picker: ^1.0.8
  file_saver: ^0.2.12
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.9
  arcore_flutter_plugin: ^0.1.0
  camera: ^0.9.8+1
  ar_core: ^0.0.2+7
  excel: ^4.0.3
  csv: ^6.0.0
  community_charts_flutter: ^1.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/database.json
