name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies and Build APK
        run: |
          cd app_produtividade
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app_produtividade/build/app/outputs/flutter-apk/app-release.apk

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          artifacts: app_produtividade/build/app/outputs/flutter-apk/app-release.apk
          tag: v0.0.1
          token: ${{ secrets.TOKEN }}
